/**
 * Predefined fields with their priority levels.
 * Fields with priority 1 are considered high priority.
 */
export const preFields = [
    { field: 'about', priority: 1 },
    { field: 'aboutMe', priority: 1 },
    { field: 'accept', priority: 1 },
    { field: 'address', priority: 1 },
    { field: 'agree', priority: 1 },
    { field: 'bio', priority: 1 },
    { field: 'city', priority: 1 },
    { field: 'confirmPassword', priority: 1 },
    { field: 'consent', priority: 1 },
    { field: 'country', priority: 1 },
    { field: 'coverPic', priority: 0 },
    { field: 'dateOfBirth', priority: 1 },
    { field: 'dob', priority: 1 },
    { field: 'description', priority: 1 },
    { field: 'education', priority: 1 },
    { field: 'email', priority: 1 },
    { field: 'firstName', priority: 1 },
    { field: 'fname', priority: 1 },
    { field: 'fullName', priority: 1 },
    { field: 'gender', priority: 1 },
    { field: 'initials', priority: 0 },
    { field: 'interests', priority: 0 },
    { field: 'isBlocked', priority: 0 },
    { field: 'isDeleted', priority: 0 },
    { field: 'isEmailVerified', priority: 0 },
    { field: 'isVerified', priority: 0 },
    { field: 'lastLoginAt', priority: 0 },
    { field: 'lastName', priority: 1 },
    { field: 'name', priority: 1 },
    { field: 'location', priority: 1 },
    { field: 'middleName', priority: 0 },
    { field: 'mobile', priority: 1 },
    { field: 'nameSurname', priority: 0 },
    { field: 'nickName', priority: 0 },
    { field: 'occupation', priority: 1 },
    { field: 'other', priority: 0 },
    { field: 'password', priority: 1 },
    { field: 'phone', priority: 1 },
    { field: 'policy', priority: 1 },
    { field: 'postalCode', priority: 1 },
    { field: 'profilePic', priority: 0 },
    { field: 'profileStatus', priority: 0 },
    { field: 'profileType', priority: 0 },
    { field: 'profileVisibility', priority: 0 },
    { field: 'resume', priority: 0 },
    { field: 'sex', priority: 1 },
    { field: 'skills', priority: 1 },
    { field: 'state', priority: 1 },
    { field: 'terms', priority: 1 },
    { field: 'timezone', priority: 0 },
    { field: 'title', priority: 0 },
    { field: 'updatedAt', priority: 0 },
    { field: 'username', priority: 0 },
    { field: 'website', priority: 0 },
    { field: 'workExperience', priority: 1 }
];